version: '3'
services:
  web:
    container_name: owm-api
    image: owm-api
    build:
        context: .
        dockerfile: Dockerfile_api
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ../api/:/opt/owm/api:rw
      - ../data/:/opt/owm/data:rw
    networks:
        owm_net:
            ipv4_address: 172.24.0.2

  front:
    container_name: owm-front
    image: owm-front
    build:
        context: .
        dockerfile: Dockerfile_front
    command: tail -f /dev/null
    ports:
        - 80:4200
    volumes:
      - ../front/:/opt/owm/front:rw
    networks:
        owm_net:
            ipv4_address: 172.24.0.3
networks:
    owm_net:
        ipam:
            driver: default
            config:
              - subnet: 172.24.0.0/29
